# pyproject.toml
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "firststage"
version = "0.1.0"
description = "MAS PoC"
readme = "README.md"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
include = ["firststage*"]
